service: procon-notifier

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: provided.al2
  stage: prod
  region: ap-northeast-1
  architecture: arm64

package: 
  artifact: target/lambda/procon-notifier/bootstrap.zip

functions:
  notify:
    handler: bootstrap
    memorySize: 128
    timeout: 10
    events:
      - schedule: cron(0 23 ? * 1 *)
    environment:
      SLACK_URL: ${env:SLACK_URL}