name: Deploy

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      SLACK_URL: ${{ secrets.SLACK_URL }}
    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --all-features

    - name: Build Package
      run: docker run --volume "$(pwd)/:/src" --workdir "/src" calavera/cargo-lambda cargo lambda build --release --arm64 --output-format zip

    - name: Serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}