name: Release

on:
  push:
    branches: [ master ]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - uses: actions-rs/cargo@v1
      name: Check format
      with:
        command: fmt
        args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - uses: actions-rs/cargo@v1
      name: Run Clippy
      with:
        command: clippy
        args: -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/cargo@v1
      name: Run Tests
      with:
        command: test
        args: --release --all-features
    - uses: Swatinem/rust-cache@v2

  deploy:
    runs-on: ubuntu-latest
    env:
      SLACK_URL: ${{ secrets.SLACK_URL }}
    needs:
      - fmt
      - clippy
      - test
    steps:
    - uses: actions/checkout@v3
    - name: Build Package
      run: docker run --volume "$(pwd)/:/src" --workdir "/src" calavera/cargo-lambda cargo lambda build --release --arm64 --output-format zip
    - name: Serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
